# Python provider with Chrome setup
providers = ["python"]

# Setup phase - install required system packages
[phases]
setup = { nixPkgs = ["python310", "chromium", "chromedriver"] }
install = "pip install -r requirements.txt"

# Start command
[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

# Basic environment variables
[variables]
PYTHONUNBUFFERED = "1"
CHROME_BIN = "/usr/bin/chromium"
