[phases.setup]
nixPkgs = [
    "python39",
    "python39Packages.pip",
    "chromium",
    "chromedriver"
]

[phases.install]
cmds = [
    "python3.9 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "python3.9 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"

[env]
PYTHONUNBUFFERED = "1"
CHROME_BIN = "/usr/bin/chromium"
PATH = "/opt/venv/bin:/usr/local/bin:/usr/bin:/bin"
VIRTUAL_ENV = "/opt/venv"
PYTHON_VERSION = "3.9"
