[phases.setup]
nixPkgs = [
    "python3",
    "python3-pip",
    "chromium",
    "chromedriver"
]

[phases.install]
aptPkgs = [
    "python3",
    "python3-pip",
    "chromium-browser"
]
cmds = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"

[env]
PYTHONUNBUFFERED = "1"
CHROME_BIN = "/usr/bin/chromium"
PATH = "/usr/local/bin:/usr/bin:/bin"
